const middleware =require( './server/MiddleWare')
const express = require('express')
const controller  =require('./controller') 
const bodyParser = require('body-parser'); 
const app = express()
app.use(express.urlencoded({extended: true}))
app.use(bodyParser.json());


app.use(middleware.task.MiddleHandler(middleware.authorization.headerAuth))
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(express.static('public'))
app.use('/api/user',controller.userRouter)
app.use(middleware.error.error);


const port=process.env.PORT || 3000

var servr =app.listen(port,()=>console.log("server start ")).on('error', (e) => {
    console.log('Error happened: ', e.message)
 });;


module.exports=servr;


//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------
