

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------

const userBusinessRoles  = require( './User')
const user=userBusinessRoles();

module.exports= {user} 

