//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


const utilities  = require( '../domain/core/utilities')
module.exports = function buildUser() {


  let result = (status, message, data) => { return { status, message, data } };

  function makeUser({ Id, Name, Age, DateCreated } = {}) {

    let data= Object.freeze({ Id, Name, Age, DateCreated:utilities.getTime() })
    //name is required failed
    if (Name.length <= 0) 
    return   result(false,"User Name must be not empty",data)

    
    //the age must be bigger than zero
    if (Age <= 0) 
    return   result(false,"Age must be bigger than 0",data)


    //All job requirements are correct
    return result(true,"All job requirements are correct",data);
  }


  return { makeUser,result };

}