
//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------



const utilities = require('../../domain/core/utilities')
const constraint = require('../../constraints')

//TODO: There some stuff miss
function check(controller) {

    if (controller == "AddUser")
        return user;

    if (controller == "getAllUser")
        return user;
}


function user(req, res, next) {
    next();
}


module.exports = {
    check
};