 
 
 
//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------



  
const upload = require("multer")
module.exports = (() => {

    
function multerConf() { 
    return { 
        storage: upload.diskStorage({  destination:  (req, file, cb) => cb(null, "./file-upload"),
            filename: (req, file, cb) =>  cb(null,  Date.now() + "_"+file.originalname)
        })
  
    }
  }


 return {multerConf}
});
 