

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------



const Repository = require('../repository')
const userUseCase = require('./User')
const serices = require('../../services');

let user = userUseCase({ usersRepository: Repository.user, serices: serices })

const usersCommenttService = Object.freeze({ user })

module.exports = usersCommenttService
