
//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


const useCase = require('./usecase')
const repository = require('./repository')


const doaminService = Object.freeze({ useCase, repository })


module.exports = doaminService


