

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


const status  = require( './status')
const dbConfig  = require( './db')
const envConfig  = require( './environment')



module.exports= {status,dbConfig,envConfig};