

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


 module.exports= {
    ACCESS_DENIED: 401,
    SUCCESS: 200,
    INVALID_TOKEN: 400,
    ERROR:404,
     
}

 
