const utilities = require('../../domain/core/utilities')
const constraint = require('../../constraints')



function headerAuth(req, res, next) {

        //get public token
        const publicToken = utilities.DecrptJwt(req.header("X-P-T"));


        //check public token
        if (publicToken.key == constraint.envConfig.config.KEY)
                next(); return true;


        //if middlerware not corrrect 
        status(constraint.status.INVALID_TOKEN).send("headerAuth/null").end()


}

 

module.exports = { headerAuth };



//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------
