const constraint = require('../../constraints')
const path = require('path');



function error(error, req, res, next) { 
 
    errorTraceLog(error)
    res.status(constraint.status.ERROR).send(error.message);
}



function errorTraceLog(ErrorObject) {
    const orig = ErrorObject.prepareStackTrace;
    Error.prepareStackTrace = (_, stack) => stack;
    const err = new Error();
    Error.captureStackTrace(err, global);

    err.stack.forEach(error => {
        
        const callee = error;
        Error.prepareStackTrace = orig; 
        const callerFile = path.relative(process.cwd(), callee.getFileName());
        const callerLine = callee.getLineNumber(); 
        console.log("---error----->", callerFile, callerLine,ErrorObject.message)
    });

}

module.exports = {
    error
};




//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------
